planning_time_limit: 10.0
max_iterations: 250
max_iterations_after_collision_free: 2
smoothness_cost_weight: 0.2
obstacle_cost_weight: 1.0
learning_rate: 0.5 #0.5
animate_path: true
add_randomness: false
smoothness_cost_velocity: 0.0
smoothness_cost_acceleration: 1.0
smoothness_cost_jerk: 0.0
hmc_discretization: 0.01
hmc_stochasticity: 0.01
hmc_annealing_factor: 0.99
use_hamiltonian_monte_carlo: false
ridge_factor: 0.007
use_pseudo_inverse: false
pseudo_inverse_ridge_factor: 1e-4
animate_endeffector: false
joint_update_limit: 0.1
collision_clearence: 0.2
collision_threshold: 0.07 #0.07
random_jump_amount: 1.0
use_stochastic_descent: true
enable_failure_recovery: false
max_recovery_attempts: 5
#trajectory_initialization_method: "quintic-spline"
trajectory_initialization_method: "fillTrajectory"
